/* =====================================================
   E-COMMERCE PRODUCT ANALYTICS SQL QUERIES
   Dataset: Online Retail
   ===================================================== */


/* -----------------------------------------------------
   1. TOTAL REVENUE
   Purpose: Calculates total revenue generated by store
----------------------------------------------------- */

SELECT 
    SUM(Quantity * UnitPrice) AS total_revenue
FROM online_retail;



/* -----------------------------------------------------
   2. MONTHLY REVENUE TREND
   Purpose: Shows revenue growth trend over time
----------------------------------------------------- */

SELECT 
    DATE_FORMAT(InvoiceDate, '%Y-%m') AS order_month,
    SUM(Quantity * UnitPrice) AS monthly_revenue
FROM online_retail
WHERE Quantity > 0
GROUP BY order_month
ORDER BY order_month;



/* -----------------------------------------------------
   3. TOP 10 PRODUCTS BY REVENUE
   Purpose: Identifies best-selling products
----------------------------------------------------- */

SELECT 
    Description,
    SUM(Quantity * UnitPrice) AS revenue
FROM online_retail
WHERE Quantity > 0
GROUP BY Description
ORDER BY revenue DESC
LIMIT 10;



/* -----------------------------------------------------
   4. REVENUE BY COUNTRY
   Purpose: Shows countries contributing most revenue
----------------------------------------------------- */

SELECT 
    Country,
    SUM(Quantity * UnitPrice) AS total_revenue
FROM online_retail
WHERE Quantity > 0
GROUP BY Country
ORDER BY total_revenue DESC;



/* -----------------------------------------------------
   5. TOP CUSTOMERS BY REVENUE
   Purpose: Identifies high-value customers
----------------------------------------------------- */

SELECT 
    CustomerID,
    SUM(Quantity * UnitPrice) AS customer_revenue
FROM online_retail
WHERE Quantity > 0
AND CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY customer_revenue DESC
LIMIT 10;



/* -----------------------------------------------------
   6. AVERAGE ORDER VALUE (AOV)
   Purpose: Measures average revenue per order
----------------------------------------------------- */

SELECT 
    SUM(Quantity * UnitPrice) / COUNT(DISTINCT InvoiceNo) AS avg_order_value
FROM online_retail
WHERE Quantity > 0;



/* -----------------------------------------------------
   7. CUSTOMER PURCHASE FREQUENCY
   Purpose: Shows number of orders per customer
----------------------------------------------------- */

SELECT 
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS number_of_orders
FROM online_retail
WHERE Quantity > 0
AND CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY number_of_orders DESC;



/* -----------------------------------------------------
   8. CUSTOMER LIFETIME REVENUE
   Purpose: Calculates total revenue per customer
----------------------------------------------------- */

SELECT 
    CustomerID,
    SUM(Quantity * UnitPrice) AS lifetime_revenue
FROM online_retail
WHERE Quantity > 0
AND CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY lifetime_revenue DESC;